version: 2

sources:
  - name: healthcare
    description: "Healthcare data source"
    database: healthcare_db
    schema: analytics
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 1, period: day}
    loaded_at_field: _etl_loaded_at
    tables:
      - name: patients
        description: "Patient demographic data"
        freshness: null
        columns:
          - name: patient_id
            description: "Primary key for patients"
            tests:
              - not_null
              - unique
          - name: first_name
            description: "First name of the patient"
          - name: last_name
            description: "Last name of the patient"
          - name: date_of_birth
            description: "Date of birth of the patient"
            tests:
              - not_null
          - name: gender
            description: "Gender of the Patient"
            tests:
              - not_null
              - accepted_values:
                  values: ['M', 'F']
      - name: vitals
        description: "Vital signs data for patients"
        freshness: null
        columns:
          - name: vital_id
            description: "Primary key for vitals"
            tests:
              - not_null
              - unique
          - name: admission_id
            description: "Foreign key to admissions table"
            tests:
              - not_null
              - relationships:
                  to: ref('admissions')
                  field: admission_id
          - name: blood_pressure
            description: "Blood pressure reading"
          - name: heart_rate
            description: "Heart rate reading"
          - name: temperature
            description: "Body temperature reading"
          - name: date
            description: "Date of the vital signs reading"
            tests:
              - not_null
      - name: admissions
        description: "Admission records for patients"
        freshness: null
        columns:
          - name: admission_id
            description: "Primary key for admissions"
            tests:
              - not_null
              - unique
          - name: patient_id
            description: "Foreign key to patients table"
            tests:
              - not_null
              - relationships:
                  to: ref('patients')
                  field: patient_id
          - name: admission_date
            description: "Date of admission"
            tests:
              - not_null
          - name: discharge_date
            description: "Date of discharge"
          - name: reason
            description: "Reason for admission"
          - name: readmitted
            description: "Readmission status"
            tests:
              - not_null
              - accepted_values:
                  values: ['Yes', 'No']
